In [1]:
import tensorflow as tf

C:\Users\Jayant\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
a = tf.constant(2)
b = tf.constant(3)
c = a + b
c

<tf.Tensor 'add:0' shape=() dtype=int32>

In [3]:
sess = tf.Session()
sess.run(c)

5

In [4]:
a1 = tf.constant([[1,2], [3,4]])
a2 = tf.constant([[2,2], [3,3]])
res = tf.matmul(a1, a2)
result, resc = sess.run([res, c])
result, resc

(array([[ 8,  8],
        [18, 18]]), 5)

In [5]:
#print(res.eval())

with tf.Session() as sess:
    print(res.eval())

[[ 8  8]
 [18 18]]


In [35]:
var1 = tf.Variable(1221)
#print(var1)
var2 = tf.Variable(3)
addition = var1 + var2
sess = tf.Session()
sess.run(tf.global_variables_initializer())
#sess.run(var1.assign(1232))
assign_object = var1.assign(1232)
sess.run(assign_object)
addition = var1 + var2
sess.run(addition)

1235

In [66]:
x = tf.placeholder(tf.int32, shape=(2, None))
y = x * tf.constant(20)  #3 or can be written x*20
print(y)
sess = tf.Session()
print(sess.run(y,feed_dict={x:[1,2,3]}))
sess.run(y, feed_dict={x:[[10,20,30],[40,50,60]]})

Tensor("mul_14:0", shape=(2, ?), dtype=int32)
[[ 20  40  60 100]
 [ 80 100 120 160]]


array([[ 200,  400,  600],
       [ 800, 1000, 1200]], dtype=int32)

In [17]:
var1=tf.Variable(100)
var2=tf.Variable(3)
sum=tf.add(var1,var2)
sess=tf.Session()
#sess1=tf.Session()
sess.run(tf.global_variables_initializer())
print(sess.run(sum))

sess.run(var1.assign(1232))
sess.run(sum)


103


1235

In [32]:

x=tf.placeholder(tf.int32,shape=(1,2))
y=x*2
sess.run(tf.global_variables_initializer())

sess.run(y,feed_dict={x:[[123]]})

array([[24,  6]])